SHOW DATABASES;

CREATE DATABASE CADASTRO;

CREATE TABLE FROTA(
	ID_FROTA INT PRIMARY KEY AUTO_INCREMENT,
	MOTORISTA VARCHAR(50) NOT NULL,
	PLACA VARCHAR(15) NOT NULL,
	KM INT NOT NULL,
	CHECK_IN_OUT ENUM('ENTRADA','SAÍDA') NOT NULL,
	OBSERVACAO VARCHAR(100) NULL,
	`DATA` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP 
);

CREATE TABLE TERCEIROS(
	ID_TERCEIROS INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(50) NOT NULL,
	DOCUMENTO INT NOT NULL,
	FINALIDADE ENUM('ENVIO','RETIRADA','OUTROS')NOT NULL,
	OBSERVACAO VARCHAR(100) NULL, 
	CONTROLE ENUM('ENTRADA','SAÍDA') NOT NULL,
	RESPONSAVEL VARCHAR(50) NOT NULL,
	`DATA` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

FROTA:

INSERT INTO FROTA VALUES (NULL,'LUIZ DOS SANTOS','DUF2354',67392,'ENTRADA','',NOW());
INSERT INTO FROTA VALUES (NULL,'Filipe Simões Catela','ATB-2337',55992,'ENTRADA','',NOW());
INSERT INTO FROTA VALUES (NULL,'Armindo Bonito','NEJ-6623',26799,'ENTRADA','',NOW());
INSERT INTO FROTA VALUES (NULL,'Léon Escobar Cesário','KIQ-4612',62605,'ENTRADA','',NOW());
INSERT INTO FROTA VALUES (NULL,'Theo Godinho','AWF-8795',84763,'ENTRADA','',NOW());
INSERT INTO FROTA VALUES (NULL,'Deivid Prates Vergueiro','MLD-4761',39862,'ENTRADA','',NOW());
INSERT INTO FROTA VALUES (NULL,'Gusttavo Keil Frias','NAQ-8963',65048,'ENTRADA','',NOW());
INSERT INTO FROTA VALUES (NULL,'Sérgio Álvaro Pardo','HPY-0484',37919,'ENTRADA','',NOW());
INSERT INTO FROTA VALUES (NULL,'Henriques Coelho','IAG-4938',48331,'ENTRADA','',NOW());
INSERT INTO FROTA VALUES (NULL,'Edson Sousa Amado','HKX-9136',64331,'ENTRADA','',NOW());
INSERT INTO FROTA VALUES (NULL,'Carlos Rangel','HPV-8793',92709,'ENTRADA','',NOW());
INSERT INTO FROTA VALUES (NULL,'Augusto Albuquerque','MKP-4255',55679,'ENTRADA','',NOW());
INSERT INTO FROTA VALUES (NULL,'Santiago Poças Camelo','MVN-4008',60827,'ENTRADA','',NOW());
INSERT INTO FROTA VALUES (NULL,'Valentim Baião','IGF-8045',76833,'ENTRADA','',NOW());
INSERT INTO FROTA VALUES (NULL,'Adonai Paula','MMV-0335',84809,'ENTRADA','',NOW());
INSERT INTO FROTA VALUES (NULL,'Ismael Milhães','JTJ-8398',57658,'ENTRADA','',NOW());
INSERT INTO FROTA VALUES (NULL,'Sebastião Aquino Lamenha','HSR-0456',47522,'ENTRADA','',NOW());
INSERT INTO FROTA VALUES (NULL,'Jadir Carneiro','IZX-8304',38270,'ENTRADA','',NOW());
INSERT INTO FROTA VALUES (NULL,'Joabe Ninharelhos','JUY-7324',84901,'ENTRADA','',NOW());
INSERT INTO FROTA VALUES (NULL,'Eden Lage','HSK-1896',26975,'ENTRADA','',NOW());
INSERT INTO FROTA VALUES (NULL,'Helder Ribeiro','GUM-2369',26082,'ENTRADA','',NOW());
INSERT INTO FROTA VALUES (NULL,'Eusébio Soares Damásio','NES-7142',105911,'ENTRADA','',NOW());
INSERT INTO FROTA VALUES (NULL,'Valentino Quintal Sacramento','AVJ-5647',23739,'ENTRADA','',NOW());
INSERT INTO FROTA VALUES (NULL,'Thiago Holanda','JZC-1349',61515,'ENTRADA','',NOW());
INSERT INTO FROTA VALUES (NULL,'Ivan Varela','AFM-4871',46075,'ENTRADA','',NOW());
INSERT INTO FROTA VALUES (NULL,'Dominique Barreira','MSP-9448',118537,'ENTRADA','',NOW());
INSERT INTO FROTA VALUES (NULL,'Jeremias Quintanilha','JDD-3401',53628,'ENTRADA','',NOW());
INSERT INTO FROTA VALUES (NULL,'Maximus Boga','NCS-5991',30167,'ENTRADA','',NOW());
INSERT INTO FROTA VALUES (NULL,'Celso Canejo','CRZ-2774',60222,'ENTRADA','',NOW());
INSERT INTO FROTA VALUES (NULL,'Ícaro Faro','ACY-9855',112060,'ENTRADA','',NOW());
INSERT INTO FROTA VALUES (NULL,'William Terra Carmo','HZK-3566',96593,'ENTRADA','',NOW());
INSERT INTO FROTA VALUES (NULL,'Arsénio Canário Andrade','LVR-1548',107448,'ENTRADA','',NOW());
INSERT INTO FROTA VALUES (NULL,'Isac Gonçalves','KRU-1454',28646,'ENTRADA','',NOW());
INSERT INTO FROTA VALUES (NULL,'Chris Rosmaninho','GQJ-4952',70872,'ENTRADA','',NOW());
INSERT INTO FROTA VALUES (NULL,'Duarte Quesado','DLV-2810',37103,'ENTRADA','',NOW());
INSERT INTO FROTA VALUES (NULL,'Emílio Chainho','MVI-8516',49538,'ENTRADA','',NOW());
INSERT INTO FROTA VALUES (NULL,'William Parreir','KON-2679',120691,'ENTRADA','',NOW());
INSERT INTO FROTA VALUES (NULL,'Tomé Lousã','JTU-2067',88538,'ENTRADA','',NOW());
INSERT INTO FROTA VALUES (NULL,'Davi Alvelos','LWH-4312',50979,'ENTRADA','',NOW());
INSERT INTO FROTA VALUES (NULL,'Marcos Candal','KCK-5943',29022,'ENTRADA','',NOW());
INSERT INTO FROTA VALUES (NULL,'Victor Aires Rabelo','NEO-3718',45266,'ENTRADA','',NOW());
INSERT INTO FROTA VALUES (NULL,'Jefferson Paião','JVE-8034',112056,'ENTRADA','',NOW());
INSERT INTO FROTA VALUES (NULL,'Gustavo Mondragão','MMS-3561',72495,'ENTRADA','',NOW());
INSERT INTO FROTA VALUES (NULL,'Marcelo Orriça','MYO-2492',122446,'ENTRADA','',NOW());
INSERT INTO FROTA VALUES (NULL,'Jordan Barcelos','NEX-5056',34159,'ENTRADA','',NOW());
INSERT INTO FROTA VALUES (NULL,'Rodolfo Narvais','MUS-5936',84328,'ENTRADA','',NOW());

TERCEIROS:









CREATE TABLE TERCEIROS(
	ID_TERCEIROS INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(50) NOT NULL,

	OBSERVACAO VARCHAR(50) NULL,
);